[package]
name = "muter"
version = "0.1.0"
authors = ["brian m. carlson <sandals@crustytoothpaste.net>"]

[build-dependencies]
autocfg = "0.1"

[dependencies]
clap = "2.32.0"

[dev-dependencies]
rand_core = "0.5"
rand_chacha = "0.2"
