Muter
=====

Muter is a tool to convert to and from various data formats, such as
hexadecimal, Base64, and URI encoding.

== Use

Muter takes a series of bytes like cat (as filenames or from standard input) and
produces a byte sequence to standard out.  The bytes are modified by the
argument to -c (--chain) that specifies the encodings to perform.

For example, a chain of `-hex:base64` decodes hex input and then re-encodes the
data in Base64.  `base64:uri` would Base64-encode the data, and then URI-encode
it, but `url64` would just encode using the URL-safe version of Base64.
A chain of `hash(sha256):hex` would hash the input data and then hex-encode the
SHA-256 hash.

Muter is designed to run on Perl 5.10.1 or newer.  It runs out of the box with
core Perl on 5.14 and newer with only slightly reduced functionality (sans
tests) and even on older versions has only minimal additional dependencies that
you probably already have.

It is available on https://metacpan.org/pod/App::Muter[CPAN].

== Examples

[source,shell-session]
----
# URI-decode some data, then HTML-encode it
$ muter -c -uri:xml,html my-data >foo.html

# Generate a subresource integrity hash
$ printf 'sha256-'; \
  curl -s https://code.jquery.com/jquery-3.2.1.js | muter -c hash,sha256:base64
sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=

# Encode a password for use with curl
$ curl https://user:$(printf 'very-complex/pass' | muter -c uri)@example.org
----

== Name

Muter comes from the Spanish verb _mudar_ and the French verb _muter_, meaning
_to mutate_, since what it does is, well, mutate data.
