pub mod ascii85;
pub mod base16;
pub mod base32;
pub mod base64;
pub mod bubblebabble;
pub mod checksum;
pub mod compress;
pub mod crlf;
pub mod hash;
pub mod hex;
pub mod identity;
pub mod lf;
pub mod quotedprintable;
#[cfg(test)]
mod tests;
pub mod uri;
pub mod uuencode;
pub mod vis;
pub mod wrap;
pub mod xml;
