name: ci
on: [push, pull_request]

jobs:
  build-buster:
    name: Linux (Debian buster amd64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-buster
    - uses: actions/upload-artifact@v2
      with:
        name: buster-amd64-deb
        path: target/assets/muter_*.deb
  build-buster-armel:
    name: Linux (Debian buster armel)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker.service
        docker version -f '{{.Server.Experimental}}'
    - uses: docker/setup-qemu-action@v1
    - run: make ci-buster
      env:
        PLATFORM: linux/arm/v5
    - uses: actions/upload-artifact@v2
      with:
        name: buster-armel-deb
        path: target/assets/muter_*.deb
  build-buster-arm64:
    name: Linux (Debian buster arm64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker.service
        docker version -f '{{.Server.Experimental}}'
    - uses: docker/setup-qemu-action@v1
    - run: make ci-buster
      env:
        PLATFORM: linux/arm64
    - uses: actions/upload-artifact@v2
      with:
        name: buster-arm64-deb
        path: target/assets/muter_*.deb
  build-oldest:
    name: Linux (oldest Rust)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-oldest
  build-stable:
    name: Linux (Rust stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-stable
      env:
        FEATURES: modern
  build-nightly:
    name: Linux (Rust nightly)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-nightly
      env:
        FEATURES: modern
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install ruby asciidoctor rust
    - run: make test-full
      env:
        FEATURES: modern


