name: ci
on: [push, pull_request]

jobs:
  build-stretch:
    name: Linux (Debian stretch)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-stretch
    - uses: actions/upload-artifact@v2
      with:
        name: stretch-deb
        path: target/assets/muter_*.deb
  build-buster:
    name: Linux (Debian buster)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-buster
    - uses: actions/upload-artifact@v2
      with:
        name: buster-deb
        path: target/assets/muter_*.deb
  build-oldest:
    name: Linux (oldest Rust)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-oldest
  build-stable:
    name: Linux (Rust stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-stable
  build-nightly:
    name: Linux (Rust nightly)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: make ci-nightly
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install ruby asciidoctor rust
    - run: make test-full


