name: ci
on: [push, pull_request]

jobs:
  build-bullseye:
    name: Linux (Debian bullseye amd64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
    - run: make ci-bullseye
    - uses: actions/upload-artifact@v6
      with:
        name: bullseye-amd64-deb
        path: target/assets/muter_*.deb
  build-bullseye-armel:
    name: Linux (Debian bullseye armel)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
    - run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker.service
        docker version -f '{{.Server.Experimental}}'
    - uses: docker/setup-qemu-action@v1
    - run: make ci-bullseye
      env:
        PLATFORM: linux/arm/v5
    - uses: actions/upload-artifact@v6
      with:
        name: bullseye-armel-deb
        path: target/assets/muter_*.deb
  build-bullseye-arm64:
    name: Linux (Debian bullseye arm64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
    - run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker.service
        docker version -f '{{.Server.Experimental}}'
    - uses: docker/setup-qemu-action@v1
    - run: make ci-bullseye
      env:
        PLATFORM: linux/arm64
    - uses: actions/upload-artifact@v6
      with:
        name: bullseye-arm64-deb
        path: target/assets/muter_*.deb
  build-oldest:
    name: Linux (oldest Rust)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
    - run: make ci-oldest
  build-stable:
    name: Linux (Rust stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
    - run: make ci-stable
      env:
        FEATURES: modern
  build-nightly:
    name: Linux (Rust nightly)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-ruby@v1
    - run: make ci-nightly
      env:
        FEATURES: modern
  build-freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-ruby@v1
    - name: Enable KVM group perms
      run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
    - run: sudo apt-get -y install vagrant vagrant-libvirt libvirt-daemon-system
    - run: sudo service libvirtd start
    - run: sudo chmod 666 /var/run/libvirt/libvirt-sock
    - run: make ci-freebsd
  build-netbsd:
    name: NetBSD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Enable KVM group perms
      run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
    - run: sudo apt-get -y install vagrant vagrant-libvirt libvirt-daemon-system
    - run: sudo service libvirtd start
    - run: sudo chmod 666 /var/run/libvirt/libvirt-sock
    - run: make ci-netbsd
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: brew install ruby asciidoctor rust
    - run: make test-full
      env:
        FEATURES: modern


